version: '3.4'

services:

  sql-data-test:
    image: mcr.microsoft.com/mssql/server:2019-latest

  chat-api-test:
    image: ${REGISTRY:-topology}/chat-api-test:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Chat/Chat.API/Dockerfile
      args:
       ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sql-data-test