version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The VIA_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     VIA_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - via-sqldata:/var/opt/mssql

  chat-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - SpaClient=http://${VIA_EXTERNAL_DNS_NAME_OR_IP}:3000
      - VALIDATE_JWT=False
      - VALIDATE_JWT_LIFETIME=False
      - ConnectionStrings__ChatDatabaseConnectionString=${VIA_DB_CONNECTION:-Server=sqldata;Database=ViaChatServer.Service.ChatDb;User Id=sa;Password=Pass@word}
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - AllowedHosts=*
    ports:
      - "44382:443"

volumes:
  via-sqldata:
    external: false

